(in-package :clobber)

(defgeneric add (table obj)
  (:method (holder obj)
    (vector-push-extend obj `(,obj holder))))

(defgeneric move (layer obj nx ny)
  (:method (layer (player player) nx ny)
    (let ((px (x-pos player))
          (py (y-pos player)))
      (setf (aref (nth layer (layers *world*)) py px) 0)
      (setf (x-pos player) nx)
      (setf (y-pos player) ny)
      (setf (aref (nth layer (layers *world*)) ny nx) 1))))

(defgeneric render (sprite x y)
  (:documentation "Renders a object onto the default sdl window.")
  (:method (sprite x y)
    (sdl:draw-surface-at-* sprite x y)))

(defgeneric create (unit)
  (:documentation "Creates any type of unit and pushes it onto that unit's stack.")
  (:method ((player player))
    (make-instance 'player))
  (:method (unit)
    (make-instance unit)))